name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22]
        os: [ubuntu-22.04, windows-2022, macos-14]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test
        shell: bash
        run: |
          npm install
          npm run prepack
          node dist/cli.js https://nodejs.org/dist/v22.7.0/node-v22.7.0-headers.tar.gz headers
          ls -l headers

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '*'
          # Required by npm publish.
          registry-url: https://registry.npmjs.org

      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install
          npx dot-json package.json version ${GITHUB_REF_NAME#v}
          npm publish --access public
          npx dot-json package.json name untar-url
          npm publish --access public --ignore-scripts
